//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DubiSouqWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class address
    {
        public int ID { get; set; }
        [Required]
        [DataType(DataType.PostalCode)]
        public int Zipcode { get; set; }
        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Address")]
        public string Address1 { get; set; }
        public int User_ID { get; set; }
        [Required]
        public string Country { get; set; }
        [Required]
        public string City { get; set; }
    
        public virtual user user { get; set; }
    }
}
