//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DubiSouqWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int ID { get; set; }
        public int Feedback1 { get; set; }
        public int Feedback2 { get; set; }
        public int Feedback3 { get; set; }
        public string Comment { get; set; }
        public int User_ID { get; set; }
    
        public virtual user user { get; set; }
    }
}
