//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DubiSouqWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public string Description { get; set; }
        public int Type_ID { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual product product { get; set; }
        public virtual report_Type report_Type { get; set; }
        public virtual user user { get; set; }
    }
}
