//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DubiSouqWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public int Product_ID { get; set; }
        public int Rate { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public string Title { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
